### ISSUE TITLE
Agree on error handling for possible erroneous input.

### ISSUE THREAD

**Issue by gbsuccar** [Alpha-Beta-Gamma/Project1#20]
I am trying to figure out what should be done for passing a grade distribution to a class, as there needs to be some way to ensure that the percentages of the grades making up the distribution don't exceed 100%.  We could just assume that the user is going to input the correct values, however I am trying to write a check in Course, however by then it would be a little late, so I'm not sure where the burden of checking should be.  However I am weary of throwing an error if the check fails when trying to add a distribution, as it would cause the site to crash.  Any ideas would be welcome.

**Comment by ghost** [comment]
I think that a perfectly viable way to do this would be to use JavaScript to validate the input on each of the forms/text boxes/drop down menus, just to make sure that each input is at least a number and contains no symbols.  And then when the data is sent though Json to java, we will check to make sure the data is in the correct range, if its not we'll send the user an error through javascript, and if it is correct we'll continue as usual.  Also, I believe that a lot of times were going to have to trust users to input the right stuff anyways, because it may be possible a class is out of 110% or 90%.  Also we can't forget about extra credit, and classes that use a point system instead of hardcore percentage system. So if a user wants to create a rouge class page out of 500% we may as well let them and no one will use it...

**Comment by gbsuccar** [comment]
I removed the mandatory percent = 100 check from the Course class.  Any percentages can be allowed now.
